export const pageTitleMap = {
  "/": "Painel",
  "/panel": "Painel",
  "/alumns": "Alunos",
  "/statistics": "Estatísticas",
  "/createAlumnEnrolled": "Matrícula de aluno",
  "/alumnProfile": "Perfil do aluno",
  "/professors": "Professores",
  "/professorProfile": "Perfil do professor",
  "/axis": "Turmas",
  "/axisDetails": "Detalhes da turma",
  "/submitCall": "Submeter chamada",
  "/lessonDetails": "Detalhes da Aula",
  "/questionaries": "Questionários",
};
